name: CI da API

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente de execução'
        required: true
        default: 'dev'


jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar o repositório
              uses: actions/checkout@v3

            - name: Configurar o Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10.12'

            - name: Instalar as dependências
              run: |
               pip install -r requirements.txt
               pip install pytest

            - name: Executar o teste
              run: pytest
    

